services:

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    command:
    - --config.file=/etc/blackbox_exporter/blackbox.yml
    volumes:
    - ./blackbox_exporter/blackbox.yml:/etc/blackbox_exporter/blackbox.yml
    ports:
    - 9115:9115

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: always
    tty: true
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090
    depends_on:
      - blackbox-exporter