global:
  scrape_interval: 15s

scrape_configs:
  - job_name: blackbox-http
    metrics_path: /probe
    params:
        module: [http_2xx]
    static_configs:
        - targets:
            - https://www.aircanada.com/home/ca/en/aco/flights # Air Canada
            - https://www.aa.com/homePage.do?locale=en_US # American Airlines
            - https://www.southwest.com # Southwest Airlines
            - https://united.com # United Airlines
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # For macOS and Windows
        replacement: host.docker.internal:9115 
        # For Linux
        # replacement: localhost:9115