global:
  scrape_interval: 15s

scrape_configs:
  - job_name: blackbox-http
    metrics_path: /probe
    params:
        module: [http_2xx]
    static_configs:
        - targets:
            - https://aircanada.com # Air Canada
            - https://aa.com # American Airlines
            - https://delta.com # Delta Air Lines
            - https://united.com # United Airlines
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9115 # For macOS and Windows
        # replacement: localhost:9115 # For Linux